apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
      - name: mail-service
        image: "daopmdean/mail-service:1.0.0"
        ports:
          - containerPort: 80
        env:
          - name: MAIL_PORT
            value: "1025"
          - name: MAIL_DOMAIN
            value: "localhost"
          - name: MAIL_HOST
            value: "mailhog"
          - name: MAIL_USERNAME
            value: ""
          - name: MAIL_PASSWORD
            value: ""
          - name: MAIL_ENCRYPTION
            value: none
          - name: FROM_NAME
            value: "John Dean"
          - name: FROM_ADDRESS
            value: "john.dean@example.com"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: mail-service
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80
